# Generated by Django 4.2 on 2024-06-21 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('kpID', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID в КиноПоиске')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('enTitle', models.CharField(max_length=200, verbose_name='Название на английском')),
                ('descr', models.TextField(max_length=1000, verbose_name='Описание')),
                ('shortDescr', models.TextField(max_length=200, verbose_name='Краткое описание')),
                ('image', models.URLField(verbose_name='Постер')),
                ('bgImage', models.URLField(verbose_name='Задний план')),
                ('rating', models.FloatField(verbose_name='Рейтинг фильма')),
                ('genres', models.CharField(max_length=300, verbose_name='Жанры')),
                ('year', models.IntegerField(verbose_name='Год выпуска')),
                ('typeOfFilm', models.CharField(max_length=200, verbose_name='Тип')),
                ('lengthOfMovie', models.IntegerField(verbose_name='Продолжительность (в минутах)')),
                ('countries', models.CharField(max_length=200, verbose_name='Страна производства')),
                ('trailerUrl', models.URLField(verbose_name='Ссылка на трейлер')),
            ],
        ),
        migrations.CreateModel(
            name='WatchedFilm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filmId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.film')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WantedFilm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filmId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.film')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
