# Generated by Django 4.2 on 2023-05-07 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('kpID', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID в КиноПоиске')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('enTitle', models.CharField(max_length=200, verbose_name='Название на английском')),
                ('descr', models.TextField(max_length=1000, verbose_name='Описание')),
                ('image', models.URLField(verbose_name='Постер')),
                ('bgImage', models.URLField(verbose_name='Задний план')),
                ('rating', models.FloatField(verbose_name='Рейтинг фильма')),
                ('genres', models.CharField(max_length=300, verbose_name='Жанры')),
                ('year', models.IntegerField(verbose_name='Год выпуска')),
                ('typeOfFilm', models.CharField(max_length=200, verbose_name='Тип')),
                ('lengthOfMovie', models.IntegerField(verbose_name='Продолжительность (в минутах)')),
                ('countries', models.CharField(max_length=200, verbose_name='Страна производства')),
            ],
        ),
        migrations.CreateModel(
            name='WatchedFilm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filmId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.film')),
            ],
        ),
        migrations.CreateModel(
            name='WantedFilm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filmId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.film')),
            ],
        ),
    ]
