# Generated by Django 4.2 on 2023-05-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='shortDescr',
            field=models.TextField(default=1, max_length=200, verbose_name='Краткое описание'),
            preserve_default=False,
        ),
    ]
