services:
  postgres_db:
    container_name: postgres_movie_tracker
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: "movie_tracker"
      POSTGRES_USER: "movie_tracker_user"
      POSTGRES_PASSWORD: "12345QWERTy"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - 15432:5432
    volumes:
      - ./psql_data:/var/lib/postgresql/data
    restart: unless-stopped